<a href="https://colab.research.google.com/github/shilz1007/shilz1007/blob/main/GeneticAlgorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
!pip install ga
!pip install pygad

  Created wheel for ga: filename=ga-0.1.1.dev0-py3-none-any.whl size=19472 sha256=c04edb3462416d8eaff80bf040625d007bea247d7a6c049f1d44d4a3c4607354
  Stored in directory: /root/.cache/pip/wheels/23/86/27/67b13c980a3673957d40a8e2cfbb89db59913324354a9abef2
Successfully built ga
     |████████████████████████████████| 53 kB 1.5 MB/s 


In [30]:
import numpy
import ga
num_weights = 6
sol_per_pop = 8
equation_input = [4,-2,3.5,5,-11,-4.7]
pop_size = (sol_per_pop , num_weights)
new_population = numpy.random.uniform(low=0 , high=1,size=pop_size)

num_generations = 5
number_of_parents_mating = 4

#Calculating the fitness function
def cal_pop_fitness(equation_input,pop):
    fitness = numpy.sum(pop*equation_input,axis = 1)
    return fitness

#selecting parents
def select_mating_pool(pop,fitness,num_parents):
    #print('pop',pop)
    #print('fitness',fitness)
    #print('num_parents',num_parents)
    parents = numpy.empty((num_parents,pop.shape[1]))
    for parent_num in range(num_parents):
       max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
       max_fitness_idx = max_fitness_idx[0][0]
       parents[parent_num, :] = pop[max_fitness_idx, :]
       fitness[max_fitness_idx] = -99999999999
    return parents   

# Crossover 
def crossover(parents,offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.init(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        # index of the first parent to mate 
        parent_idx = k%parents.shape[0]
        #index of second parent to mate 
        parent2_idx = (k+1)%parents.shape[0]
        #first half of the gene taken from the parent
        offspring[k,0 : crossover_point] = parents[parent1_idx, 0:crossover_point]
        #second half of the gene taken from another parent
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
        return offspring
def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-0-1,1.0,1)
        offspring_crossover[idx,4] = offspring_crossover[idx,4] + random_value
    return offspring_crossover

for generation in range(num_generations):
    print('Generation : ',generation)

    fitness = cal_pop_fitness(equation_input,new_population)
    print('fitness values: ',fitness)

    parents = select_mating_pool(new_population,fitness,number_of_parents_mating)
    print('selected parents :',parents)
    
    offspring_crossover = crossover(parents,offspring_size=(pop_size[0]-parents.shape[0], num_weights))
    print('crossover ',offspring_crossover)
                                        
    offspring_mutation = mutation(offspring_crossover)
    print('mutation ',offspring_mutation)

    print('best result after' + 'generation') 
   #        generation + numpy.where(fitness == numpy.max(fitness))

    #creating new population based on parents and offspring
 #   new_population[0:parents.shape[0], :] = parents
    new_population[0:parents.shape[0], :] = parents 
    new_population[parents.shape[0]:, :] = offspring_mutation





Generation :  0
fitness values:  [ 2.21866369  1.03513888 -5.87086326  0.66727433 -1.42919771  1.70146135
 -8.75057394 -0.22735814]
selected parents : [[0.95332163 0.25523407 0.04785274 0.72575128 0.43389169 0.02289086]
 [0.08169364 0.07198365 0.82656205 0.95531453 0.29661842 0.61448577]
 [0.22917645 0.74846613 0.78098989 0.80092311 0.19949177 0.62304368]
 [0.85996141 0.0570872  0.96591173 0.18778948 0.35401635 0.65613947]]


AttributeError: ignored