<a href="https://colab.research.google.com/github/shilz1007/shilz1007/blob/main/SimpleGA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

num_generation = 5
gene = 10
sol_per_pop = 8
pop_size = (sol_per_pop,gene)
num_parents = 4
#test = np.empty((num_parents,sol_per_pop))
#print('test',test)
parent_size =(num_parents,gene)

tot_pop = np.random.randint(2,size=pop_size)
#print('data type of tot_pop',type(tot_pop))
def fitness_test(tot_pop):
      fitness = np.sum(tot_pop,axis=1)
      return fitness  
def selecting_parent(fitness_result,tot_pop):
    for x in range(num_parents):
        max_fitness = np.where(fitness_result == np.max(fitness_result))
        max_fitness = max_fitness[0][0]
        temp = tot_pop[max_fitness,:]
        parents[x,:] = temp
        fitness_result[max_fitness] = -9
    return parents      
def crossover(parents,new_pop):
    new_pop[0:4] = parents
    new_pop[4,:] = np.concatenate((parents[0,0:5],parents[1,5:10]),axis=0)
    new_pop[5,:] = np.concatenate((parents[1,0:5],parents[0,5:10]),axis=0)
    new_pop[6,:] = np.concatenate((parents[2,0:5],parents[3,5:10]),axis=0)
    new_pop[7,:] = np.concatenate((parents[3,0:5],parents[2,5:10]),axis=0)
    #new_pop[8,:] = np.concatenate((parents[0,0:5],parents[3,5:10]),axis=0)
    #new_pop[9,:] = np.concatenate((parents[3,0:5],parents[0,5:10]),axis=0)
    #print('new pop final',new_pop)
    return new_pop  

def mutation(new_pop):
    for i in range(4,8):
        #print('new_pop before',new_pop[i,])
        temp = new_pop[i,]
        #print('before temp',temp)
        #print('i',i)
        for j in range(5,10):
           if temp[j] == 0:
              #print('temp j', temp[j])
              temp[j] = 1
           elif temp[j] == 1:
              #print('in elif')
              #print('temp[j]',temp[j])
              temp[j] = 0   
              #print('temp after',temp) 
        new_pop[i,] = temp
        #print('new_pop after ',new_pop[i,]) 
    return new_pop   
def decimal(new_pop):
    new_rule = np.random.randint(1,size=8)
    for k in range(8):
       a = new_pop[k,:]
       ar = [int(i) for  i in a]
       ar  = ar[::-1]
       res = []
       for i in range(len(ar)):
           res.append(ar[i]*(2**i))
       sum_res = sum(res) 
       new_rule[k] = sum_res 

       print('Decimal Number is : ',sum_res) 
    print('Decimal Number is : ',sum_res)
    return new_rule      

old_rule = decimal(tot_pop)
print('old rules',old_rule)
for generation in range(num_generation):
    print('tot_pop',tot_pop)
    fitness_result = fitness_test(tot_pop) 
    print('fitness_result',fitness_result)
    parents = np.random.randint(2,size=parent_size)
    parents = selecting_parent(fitness_result,tot_pop)
    print('parents',parents)
    new_pop = np.random.randint(2,size=pop_size)
    new_pop = crossover(parents,new_pop)
    print('after crossover new_pop',new_pop)
    new_pop = mutation(new_pop)
    print('after mutation new_pop',new_pop)
    tot_pop = new_pop
    print('tot_pop after each generation ',tot_pop)

final_rule=decimal(new_pop)
print('final rule',final_rule)









   
       

Decimal Number is :  27
Decimal Number is :  321
Decimal Number is :  863
Decimal Number is :  323
Decimal Number is :  674
Decimal Number is :  406
Decimal Number is :  100
Decimal Number is :  702
Decimal Number is :  702
old rules [ 27 321 863 323 674 406 100 702]
tot_pop [[0 0 0 0 0 1 1 0 1 1]
 [0 1 0 1 0 0 0 0 0 1]
 [1 1 0 1 0 1 1 1 1 1]
 [0 1 0 1 0 0 0 0 1 1]
 [1 0 1 0 1 0 0 0 1 0]
 [0 1 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 1 0 0]
 [1 0 1 0 1 1 1 1 1 0]]
fitness_result [4 3 8 4 4 5 3 7]
parents [[1 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 1 1 1 1 1 0]
 [0 1 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 1 1 0 1 1]]
after crossover new_pop [[1 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 1 1 1 1 1 0]
 [0 1 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 1 1 0]
 [1 0 1 0 1 1 1 1 1 1]
 [0 1 1 0 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 1 1 0]]
after mutation new_pop [[1 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 1 1 1 1 1 0]
 [0 1 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 

In [47]:
a = input('Enter a binary number : ')
ar = [int(i) for  i in a]
ar  = ar[::-1]
res = []
for i in range(len(ar)):
    res.append(ar[i]*(2**i))
sum_res = sum(res)      
print('Decimal Number is : ',sum_res) 




Enter a binary number : 1001001001111
Decimal Number is :  4687
